### ISSUE TITLE
error while build npm run build:spa-dev

### ISSUE THREAD

**Issue by ihteandr** [nglibs/example-app#4]
I use commands "npm run build:spa-dev" and "npm run build:spa-prod"
and get this:
[16:22:41] Using gulpfile ~\Documents\helpers\universal\gulpfile.js
[16:22:41] Starting 'clean'...
[16:22:41] Starting 'clean:public'...
[16:22:41] Finished 'clean:public' after 11 ms
[16:22:41] Starting 'clean:server'...
[16:22:41] Finished 'clean:server' after 6.12 ms
[16:22:41] Starting 'clean:cache'...
[16:22:41] Finished 'clean:cache' after 2.61 ms
[16:22:41] Starting 'clean:temp'...
[16:22:41] Finished 'clean:temp' after 1.79 ms
[16:22:41] Finished 'clean' after 29 ms
[16:22:44] Using gulpfile ~\Documents\helpers\universal\gulpfile.js
[16:22:44] Starting 'build:spa-dev'...
[16:22:44] Starting 'dummy'...
[16:22:44] Finished 'dummy' after 1.83 ms
[16:22:44] Starting 'bundle:spa-dev'...
[16:22:45] 'bundle:spa-dev' errored after 384 ms
[16:22:45] SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\Documents\helpers\universal\node_modules\@ngtools\webpack\src\index.js:30:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
[16:22:45] 'build:spa-dev' errored after 403 ms

**Comment by fulls1z3** [comment]
@ihteandr this issue is happening because of UglifyJS. Can you please verify which version of UglifyJS you have in `node_modules` directory?

According to the original package.json, UglifyJS should have been fixed to version `v2.8.22`. Higher versions have more or less a different API and not backwards-compatible.

**Comment by ihteandr** [comment]
I have 2.8.22 version on uglify, I check in package json and in node_modules
